logLevel: debug # 日志级别
port: 32767 # 监听端口
paintDelay: 1 # 画图冷却 (ms)
validationPaste: 'LSPaintBoard-2025' # 云剪切板验证码
useDB: true # 是否使用数据库
clearBoard: true # 是否在启动时清空画板
ticksPerSecond: 128 # 每秒刷新次数
# maxWebSocketPerIP: 7 # 每个 IP 最大 WebSocket 连接数
# key: ./key.pem # SSL证书
# cert: ./cert.pem # SSL证书
# activityStartTime: 0 # 毫秒为单位，活动开始时间
# activityEndTime: 1767196800000 # 活动结束时间